### ISSUE TITLE
problems with linking to mom4p1 guide from userguide

### ISSUE THREAD

**Issue by StephenGriffies** [mom-ocean/mom-ocean.github.io#13]
I am having troubles with the markdown or such with the mom4p1.pdf link in _docs/user_guide.md.  Can someone help?

**Comment by aidanheerdegen** [comment]
That item was indented, so markdown doesn't see it as part of the list, but as quoted text.

Fixed in this commit https://github.com/mom-ocean/mom-ocean.github.io/commit/0c7968c3e59bacf46cf3e6f3b86ea3af36ddcc48

**Comment by StephenGriffies** [comment]
Wonderful.  Thanks much @aidanheerdegen

**Comment by aidanheerdegen** [comment]
No worries. Using an editor that can preview markdown (I use Microsoft Visual Code) can be a big help.
