### ISSUE TITLE
Quick start guide links to non-existent "download instructions"

### ISSUE THREAD

**Issue by bpherzog** [mom-ocean/mom-ocean.github.io#14]
In the [quick start guide](https://mom-ocean.github.io/docs/quick-start-guide/), there are many references to "download instructions" which links to http://www.mom-ocean.org/web/downloads. However, this site is inaccessible. The link should be updated to include the appropriate link, or remove all the references to the instructions.

**Comment by StephenGriffies** [comment]
@aidanheerdegen  is this something you could do?  I am swamped with teaching for a while...

**Comment by aidanheerdegen** [comment]
I'll see what I can do

**Comment by aidanheerdegen** [comment]
I've made a new downloads page

https://mom-ocean.github.io/downloads/

modelled off the old one

https://mdl-mom5.herokuapp.com/web/downloads

I've removed the idea of "release versions" as they're so old and we seem to have moved away from that approach.

I've added a link to downloads in the top menu as well, and changed all the places I could find references to the old link (and some other links to the mom-ocean.org site).

Unfortunately the TPAC THREDDS server where the test data is served form is down at the moment, but Paola is looking into that.

http://portal.sf.utas.edu.au/thredds/catalog/momtest/catalog.html

**Comment by aidanheerdegen** [comment]
Ok. The UTAS server is back up so I'll close this issue.

**Comment by StephenGriffies** [comment]
Thanks so much for this @aidanheerdegen !

**Comment by aidanheerdegen** [comment]
No worries. It was mostly good timing. The HPC systems were down for maintenance associated with an upgrade, so I was at a bit of a loose end.
