### ISSUE TITLE
Banner picture on homepage is too dark

### ISSUE THREAD

**Issue by aidanheerdegen** [mom-ocean/mom-ocean.github.io#4]
@StephenGriffies thought the banner picture on the home page is too dark

https://github.com/mom-ocean/MOM5/issues/222#issuecomment-411947345

This is due to the 

```css
overlay_filter: "0.5"
```

property on the header image

**Comment by aidanheerdegen** [comment]
Fixed https://github.com/mom-ocean/mom-ocean.github.io/commit/f341b918dd72531298bfbde5dc8d5455a5a155b2

**Comment by StephenGriffies** [comment]
Brilliant!  Thanks for that @aidanheerdegen  Picture is much more dramatic now, albeit a bit less moody... :-)
