### ISSUE TITLE
Page build failure

### ISSUE THREAD

**Issue by aidanheerdegen** [mom-ocean/mom-ocean.github.io#8]
When the site was updated the following error was reported:
```
The tag `include_cached` on line 16 in `/_layouts/default.html` is not a recognized Liquid tag
```

**Comment by aidanheerdegen** [comment]
Due to a change in theme

https://github.com/mmistakes/minimal-mistakes/issues/1875

**Comment by StephenGriffies** [comment]
Thanks.  This is good.  

I now need to correct some bad links on the Userguide to the pdf documents.  Hopefully all will work this time around.
